FROM php:8-fpm

LABEL Author="PRATCHAYAPOL <pratchayapol.ja@rmuti.ac.th>" version="latest" org.opencontainers.image.authors="pratchayapol.ja@rmuti.ac.th"

# ติดตั้งส่วนขยาย PHP ที่จำเป็น รวมถึง zip และ git
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libjpeg-dev \
    libpng-dev \
    libzip-dev \
    zip \
    git \
    && docker-php-ext-install curl sockets zip \
    && docker-php-ext-install mysqli pdo pdo_mysql

# คัดลอก Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# ตั้งค่าตัวแปรสิ่งแวดล้อมเพื่อให้ Composer ทำงานได้ในโหมด root
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /var/www/html

# คัดลอกไฟล์โปรเจกต์ไปยัง container
COPY . .

# รันคำสั่ง composer install
RUN composer install --no-interaction --prefer-dist --no-scripts --no-dev

# Set permissions for /var/www/html (use chmod)
RUN chmod -R 777 /var/www/html

COPY php.ini /usr/local/etc/php/
