FROM nginx:latest

LABEL Author="PRATCHAYAPOL <pratchayapol.ja@rmuti.ac.th>" version="latest" org.opencontainers.image.authors="pratchayapol.ja@rmuti.ac.th"

# Install required dependencies for GD extension
RUN apt-get update && apt-get install -y \
    libjpeg-dev \
    libpng-dev \
    && rm -rf /var/lib/apt/lists/*

#COPY . .

#COPY ../default.conf/default.conf /etc/nginx/conf.d/default.conf

#COPY ../default.conf/nginx.conf /etc/nginx/nginx.conf

COPY ../src /var/www/html

RUN chmod -R 777 /var/www/html

# Expose ports 80
EXPOSE 80
